// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwEM0oSHUsYfsto_2ner0jNW-eJmhBXd4',
    appId: '1:214943613320:web:fa32049f13c1eebbfafa3d',
    messagingSenderId: '214943613320',
    projectId: 'hallowed-chain-457509-g7',
    authDomain: 'hallowed-chain-457509-g7.firebaseapp.com',
    storageBucket: 'hallowed-chain-457509-g7.firebasestorage.app',
    measurementId: 'G-HJX3K3CNL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_oUQJzt31LAwouqhXWtwZ-BT1CE5oCuw',
    appId: '1:214943613320:android:1391fccafa5be331fafa3d',
    messagingSenderId: '214943613320',
    projectId: 'hallowed-chain-457509-g7',
    storageBucket: 'hallowed-chain-457509-g7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVNU_FsrZ3-_xDY0iwgTUx0SMdcb-DPWg',
    appId: '1:214943613320:ios:26072d52ba99d5fdfafa3d',
    messagingSenderId: '214943613320',
    projectId: 'hallowed-chain-457509-g7',
    storageBucket: 'hallowed-chain-457509-g7.firebasestorage.app',
    iosClientId: '214943613320-hakmpn9opabe69cgudll2qc6puv8le8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVNU_FsrZ3-_xDY0iwgTUx0SMdcb-DPWg',
    appId: '1:214943613320:ios:26072d52ba99d5fdfafa3d',
    messagingSenderId: '214943613320',
    projectId: 'hallowed-chain-457509-g7',
    storageBucket: 'hallowed-chain-457509-g7.firebasestorage.app',
    iosClientId: '214943613320-hakmpn9opabe69cgudll2qc6puv8le8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwEM0oSHUsYfsto_2ner0jNW-eJmhBXd4',
    appId: '1:214943613320:web:a227f93647433c65fafa3d',
    messagingSenderId: '214943613320',
    projectId: 'hallowed-chain-457509-g7',
    authDomain: 'hallowed-chain-457509-g7.firebaseapp.com',
    storageBucket: 'hallowed-chain-457509-g7.firebasestorage.app',
    measurementId: 'G-N7GRH0S1LN',
  );

}